#!/bin/bash

HERE=$(dirname "$(readlink "$0")")
REPO=$(basename "`pwd`")

case "$(uname -s)" in
    Darwin)
        EMACS=/opt/local/bin/emacs
        ;;

    Linux)
        EMACS=emacs
        ;;

    CYGWIN*|MINGW32*|MSYS*)
        EMACS=emacs
        ;;

    # Add here more strings to compare
    # See correspondence table at the bottom of this answer

    *)
        echo 'Unsupported OS'
        exit 2
        ;;
esac

${EMACS} --name="smagit: $REPO" -q --load $HERE/init.el
